owner: sybila
remote_repository_url: "https://github.com/sybila/galaxytools/tree/master/tools/ebcsgen"
homepage_url: "https://github.com/sybila/eBCSgen"
categories:
  - Systems Biology
repositories:
  ebcsgen_generate_transition_system:
    description: "Generate transition system of the given BCSL model."
    include:
      - ebcsgen_generate_ts.xml
      - ebcsgen_generate_ts.py
      - test-data/simple.bcsl.model
      - macros.xml
  ebcsgen_pctl_model_checking:
    description: "Explicit PCTL model checking of given transition system."
    include:
      - ebcsgen_pctl_model_checking.xml
      - ebcsgen_pctl_model_checking.py
      - test-data/pctl_model_checking.bcsl.ts
      - macros.xml
  ebcsgen_simulation:
    description: "Simulation of the given BCSL model."
    include:
      - ebcsgen_simulate.xml
      - ebcsgen_simulate.py
      - test-data/repressilator.bcsl.model
      - test-data/simulation_determ.csv
      - macros.xml
  ebcsgen_ctl_model_checking:
    description: "Simulation of the given BCSL model."
    include:
      - ebcsgen_ctl_model_checking.xml
      - ebcsgen_ctl_model_checking.py
      - test-data/pctl_model_checking.bcsl.ts
      - macros.xml
